### ISSUE TITLE
Update to gemBS v3

### ISSUE THREAD

**Issue by berguner** [ENCODE-DCC/wgbs-pipeline#1]
Hello,

As far as I can tell you created this pipeline based on gemBS v2. Are you planning to update it for gemBS v3?

Best,
Bekir

**Comment by Bek** [comment]
We are updating the workflow to work with GEM3. Working Dockerfile is in the following branch: https://github.com/ENCODE-DCC/wgbs-pipeline/tree/gemBS_v2. Built image can be pulled from quay.io/encode-dcc/wgbs-pipeline:gemBS_v2

**Comment by berguner** [comment]
Thanks for answering. I am looking forward for the update.

**Comment by paul-sud** [comment]
Hi @berguner , the pipeline is now in a final state using GEM3 if you are still interested.

**Comment by berguner** [comment]
Thank you Paul, I will give it a try.
