### ISSUE TITLE
[question] difference between verison 1 and version 2 wdl?

### ISSUE THREAD

**Issue by vsoch** [ENCODE-DCC/wgbs-pipeline#2]
I see two wdl pipeline files:

```bash
$ ls wgbs-pipeline*
wgbs-pipeline-v2.wdl  wgbs-pipeline.wdl
```
along with the test.wdl (which I believe is the one I should use) and some other ones:

```bash
$ ls *.wdl
bs-call.wdl  mapping.wdl  test.wdl  wgbs-pipeline-v2.wdl  wgbs-pipeline.wdl
```
How do I know what these are, and which to use? I think if there were two clearly "main" pipelines in the folder, one named according to the repo name (wgbs-pipeline.wdl) and the other for testing "test.wdl") this would be intuitive. Can we discuss these other files and how they are used?

**Comment by Bek** [comment]
Old pipeline is obsolete now, the current one doesn't have the old wdl scripts
