### ISSUE TITLE
[bug] localization error when using Cromwell via Docker

### ISSUE THREAD

**Issue by vsoch** [ENCODE-DCC/wgbs-pipeline#3]
This isn't an issue / bug proper, but rather just an issue that I can link in the documentation to explain the issue with using cromwell inside Docker. I'll open and close likely when I get it fleshed out fully:

```bash
Localization via hard link has failed: /cromwell-executions/wgbs/47d02aff-5371-478e-a412-54189e06b303/call-flatten_/inputs/-1474066501/flowcell_1_1_1.fastq.gz -> /opt/data/fastq/flowcell_1_1_1.fastq.gz: Invalid cross-device link
```
carry on! And thanks to @Bek for the help and pointing this out earlier!

**Comment by Bek** [comment]
This was due to managing mounted file systems in the case of running a container inside another container. Cromwell running inside a container will try to launch another container for a task when running locally.
