### ISSUE TITLE
A question about the differences between wgbs-pipeline and dna-me-pipeline

### ISSUE THREAD

**Issue by QianhuiWan** [ENCODE-DCC/wgbs-pipeline#57]
Hello, I found `dna-me-pipeline` and `wgbs-pipeline` from ENCODE, what are the differences between these 2 pipelines in terms of analysing WGBS data? Thank you so much! Best regards, Qianhui

**Comment by paul-sud** [comment]
Hi Qianhui,

`dna-me-pipeline` is older and only runs on DNAnexus. It was used to process ENCODE data some time ago. That pipeline uses Bowtie2 for alignment and Bismark for methylation calls, among other software. You can find a high-level schematic here: https://www.encodeproject.org/pipelines/ENCPL985BLO/

`wgbs-pipeline` is newer and will be used to process ENCODE data going forward. It is based on WDL and can run on multiple platforms. It uses [gemBS](https://github.com/heathsc/gemBS) for alignment and methylation calling and also includes smoothing of CpG methylation values via [Bsmooth](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-10-r83).

I hope that helps, please let me know if you have any additional questions.

Best,

Paul

**Comment by QianhuiWan** [comment]
Hi Paul, 

Thank you for your answer which is very helpful. I will try `WGBS-pipeline` for my data. 

Best regards
Qianhui

**Comment by paul-sud** [comment]
Glad to help. I'll close this issue, but please feel free to reopen if you have any further questions.
